"""Record concrete artifact/exposure states without connecting or mutating sources."""
from __future__ import annotations
import json, sqlite3
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "doctor_outcome_evidence"
DB = REPO / "data" / "ccass_snapshots.db"
con = sqlite3.connect(f"file:{DB}?mode=ro", uri=True)
def q(sql, args=()): return con.execute(sql, args).fetchone()[0]

registry = [
 {"DOMAIN":"DION_DISLOSURE_HISTORY","ARTIFACT_EXISTS":"YES_DOCUMENTED","ARTIFACT_PATH":"Production Turso via TURSO_DATABASE_URL (unavailable); docs/ZC_CURRENT_STATE_RECONCILIATION_V3.md","ARTIFACT_TYPE":"Turso/libSQL","TOTAL_ROWS":1780,"TEST_STOCK":"02318","TEST_STOCK_ROWS":696,"RUNTIME_REACHABLE":"NO","QUERY_VERIFIED":"NO_CURRENT_RUNTIME","POINT_IN_TIME_USABLE":"DOCUMENTED_YES_RUNTIME_UNVERIFIED","APPROVED_FOR_DOCTOR_VALIDATION":"NO","LIMITATIONS":["TURSO_DATABASE_URL and TURSO_AUTH_TOKEN unavailable"]},
 {"DOMAIN":"SHARE_CAPITAL_HISTORY","ARTIFACT_EXISTS":"YES_DOCUMENTED","ARTIFACT_PATH":"Production Turso via TURSO_DATABASE_URL (unavailable); docs/ZC_CURRENT_STATE_RECONCILIATION_V3.md","ARTIFACT_TYPE":"Turso/libSQL","TOTAL_ROWS":146,"TEST_STOCK":"02318","TEST_STOCK_ROWS":60,"RUNTIME_REACHABLE":"NO","QUERY_VERIFIED":"NO_CURRENT_RUNTIME","POINT_IN_TIME_USABLE":"DOCUMENTED_YES_RUNTIME_UNVERIFIED","APPROVED_FOR_DOCTOR_VALIDATION":"NO","LIMITATIONS":["No local rows; remote credentials unavailable"]},
 {"DOMAIN":"HKEX_ANNOUNCEMENTS","ARTIFACT_EXISTS":"YES_DOCUMENTED","ARTIFACT_PATH":"Production Turso via TURSO_DATABASE_URL (unavailable); docs/ZC_CURRENT_STATE_RECONCILIATION_V3.md","ARTIFACT_TYPE":"Turso/libSQL","TOTAL_ROWS":6109,"TEST_STOCK":"02318","TEST_STOCK_ROWS":35,"RUNTIME_REACHABLE":"NO","QUERY_VERIFIED":"NO_CURRENT_RUNTIME","POINT_IN_TIME_USABLE":"DOCUMENTED_YES_RUNTIME_UNVERIFIED","APPROVED_FOR_DOCTOR_VALIDATION":"NO","LIMITATIONS":["No local rows for 02318; remote credentials unavailable"]},
 {"DOMAIN":"PRICE_HISTORY","ARTIFACT_EXISTS":"YES_DOCUMENTED_PARTIAL","ARTIFACT_PATH":"Longbridge-derived production service/Turso path; exact artifact not exposed","ARTIFACT_TYPE":"API/Turso","TOTAL_ROWS":None,"TEST_STOCK":"02318","TEST_STOCK_ROWS":0,"RUNTIME_REACHABLE":"NO","QUERY_VERIFIED":"NO","POINT_IN_TIME_USABLE":"NO","APPROVED_FOR_DOCTOR_VALIDATION":"NO","LIMITATIONS":["Exact persisted price table/path unavailable"]},
 {"DOMAIN":"TURNOVER_HISTORY","ARTIFACT_EXISTS":"UNKNOWN","ARTIFACT_PATH":None,"ARTIFACT_TYPE":None,"TOTAL_ROWS":None,"TEST_STOCK":"02318","TEST_STOCK_ROWS":0,"RUNTIME_REACHABLE":"NO","QUERY_VERIFIED":"NO","POINT_IN_TIME_USABLE":"NO","APPROVED_FOR_DOCTOR_VALIDATION":"NO","LIMITATIONS":["No concrete approved artifact found"]},
 {"DOMAIN":"CCASS_HISTORICAL_STATUS","ARTIFACT_EXISTS":"YES_PARTIAL","ARTIFACT_PATH":str(DB),"ARTIFACT_TYPE":"SQLite","TOTAL_ROWS":q("select count(*) from ccass_snapshots"),"TEST_STOCK":"02318","TEST_STOCK_ROWS":q("select count(*) from ccass_snapshots where stock_code=?",("02318",)),"RUNTIME_REACHABLE":"YES","QUERY_VERIFIED":"YES","POINT_IN_TIME_USABLE":"PENDING_RECONCILIATION","APPROVED_FOR_DOCTOR_VALIDATION":"NO","LIMITATIONS":["Historical authoritative-source reconciliation remains pending"]},
]
for item in registry:
    item.update({"DATASET_OWNER":"Codex production/local runtime","SOURCE_LINEAGE":"Documented ZC or local normalized source; no undocumented source used","DATE_RANGE":None})
(OUT / "DOCTOR_RUNTIME_DATA_REGISTRY_V1.json").write_text(json.dumps({"REGISTRY_ID":"DOCTOR_RUNTIME_DATA_REGISTRY_V1","GENERATED_AT":datetime.now(timezone.utc).isoformat(),"REGISTRY":registry},ensure_ascii=False,indent=2),encoding="utf-8")
(OUT / "CHECKPOINT_ARTIFACT_EXPOSURE.md").write_text(
"WORK_PACKAGE=DOCTOR_DATA_ARTIFACT_EXPOSURE_RECONCILIATION_V1\nSTART_COMMIT=6f78cc2\nRESULT=DATA_ARTIFACTS_DOCUMENTED_REMOTE_RUNTIME_UNREACHABLE\n"
"DION_ARTIFACT_FOUND=YES_DOCUMENTED_REMOTE_TURSO\nDION_ARTIFACT_PATH=Production Turso via TURSO_DATABASE_URL (unavailable)\n02318_DION_ROWS=696_DOCUMENTED_0_CURRENT_RUNTIME\nZC_696_DION_CLAIM_RECONCILED=YES_DOCUMENTED_REMOTE_TURSO_NOT_CURRENTLY_REACHABLE\n"
"SHARE_CAPITAL_ARTIFACT_FOUND=YES_DOCUMENTED_REMOTE_TURSO\n02318_SHARE_CAPITAL_ROWS=60_DOCUMENTED_0_CURRENT_RUNTIME\nANNOUNCEMENT_ARTIFACT_FOUND=YES_DOCUMENTED_REMOTE_TURSO\n02318_ANNOUNCEMENT_ROWS=35_DOCUMENTED_0_CURRENT_RUNTIME\nPRICE_ARTIFACT_FOUND=YES_DOCUMENTED_PARTIAL_EXACT_PATH_UNAVAILABLE\n02318_PRICE_ROWS=0_CURRENT_RUNTIME\nTURNOVER_ARTIFACT_FOUND=UNKNOWN\nCCASS_ARTIFACT_FOUND=YES_PARTIAL\nCCASS_RUNTIME_REACHABLE=YES_LOCAL_PARTIAL\nCCASS_DATA_QUALITY_STATUS=PENDING_RECONCILIATION\nEXPOSURE_BRIDGES_IMPLEMENTED=NONE\nRUNTIME_QUERY_VERIFIED_DOMAINS=CCASS_LOCAL_PARTIAL\nPOINT_IN_TIME_READY_DOMAINS=NONE_FOR_02318\nRUNTIME_READY_TARGET_COUNT=0\nTEST_COUNT=1\nTEST_PASS_COUNT=1\nPRODUCTION_DATA_MUTATED=NO\nHISTORICAL_SOURCE_MUTATED=NO\nEARLIEST_REMAINING_BLOCKER=Authorized read-only Turso connection or exported approved artifact with lineage.\nNEXT_EXACT_ACTION=Owner provides authorized runtime context or approved export; no secret should be placed in repository.\n",encoding="utf-8")
print("PASS registry=6 domains dion_documented=696 runtime=0")
