[server]
headless = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#006D77"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F3F7F8"
textColor = "#172B35"
